import { Role } from "@prisma/client";

export const PERMISSIONS = {
  // Dashboard
  VIEW_DASHBOARD: "VIEW_DASHBOARD",

  // Shipments
  CREATE_SHIPMENT: "CREATE_SHIPMENT",
  VIEW_SHIPMENT: "VIEW_SHIPMENT",
  EDIT_SHIPMENT: "EDIT_SHIPMENT",
  DELETE_SHIPMENT: "DELETE_SHIPMENT",

  // Containers
  CREATE_CONTAINER: "CREATE_CONTAINER",
  VIEW_CONTAINER: "VIEW_CONTAINER",
  EDIT_CONTAINER: "EDIT_CONTAINER",
  DELETE_CONTAINER: "DELETE_CONTAINER",

  // Transport Trips
  CREATE_TRIP: "CREATE_TRIP",
  VIEW_TRIP: "VIEW_TRIP",
  EDIT_TRIP: "EDIT_TRIP",
  DELETE_TRIP: "DELETE_TRIP",

  // Documents
  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  VIEW_DOCUMENT: "VIEW_DOCUMENT",
  DELETE_DOCUMENT: "DELETE_DOCUMENT",

  // Users
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_USERS: "VIEW_USERS",

  // Settings
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  VIEW_SETTINGS: "VIEW_SETTINGS",

  // Companies
  MANAGE_COMPANIES: "MANAGE_COMPANIES",
  VIEW_COMPANIES: "VIEW_COMPANIES",

  // Traders
  CREATE_TRADER: "CREATE_TRADER",
  VIEW_TRADER: "VIEW_TRADER",
  EDIT_TRADER: "EDIT_TRADER",
  DELETE_TRADER: "DELETE_TRADER",

  // Gates
  CREATE_GATE: "CREATE_GATE",
  VIEW_GATE: "VIEW_GATE",
  EDIT_GATE: "EDIT_GATE",
  DELETE_GATE: "DELETE_GATE",

  // Ports
  CREATE_PORT: "CREATE_PORT",
  VIEW_PORT: "VIEW_PORT",
  EDIT_PORT: "EDIT_PORT",
  DELETE_PORT: "DELETE_PORT",

  // Depots
  CREATE_DEPOT: "CREATE_DEPOT",
  VIEW_DEPOT: "VIEW_DEPOT",
  EDIT_DEPOT: "EDIT_DEPOT",
  DELETE_DEPOT: "DELETE_DEPOT",

  // Item Types
  CREATE_ITEM_TYPE: "CREATE_ITEM_TYPE",
  VIEW_ITEM_TYPE: "VIEW_ITEM_TYPE",
  EDIT_ITEM_TYPE: "EDIT_ITEM_TYPE",
  DELETE_ITEM_TYPE: "DELETE_ITEM_TYPE",

  // Company Items
  CREATE_COMP_ITEM: "CREATE_COMP_ITEM",
  VIEW_COMP_ITEM: "VIEW_COMP_ITEM",
  EDIT_COMP_ITEM: "EDIT_COMP_ITEM",
  DELETE_COMP_ITEM: "DELETE_COMP_ITEM",

  // Sub Companies
  CREATE_SUB_COMPANY: "CREATE_SUB_COMPANY",
  VIEW_SUB_COMPANY: "VIEW_SUB_COMPANY",
  EDIT_SUB_COMPANY: "EDIT_SUB_COMPANY",
  DELETE_SUB_COMPANY: "DELETE_SUB_COMPANY",

  // Transport Companies
  CREATE_TRANSPORT_COMPANY: "CREATE_TRANSPORT_COMPANY",
  VIEW_TRANSPORT_COMPANY: "VIEW_TRANSPORT_COMPANY",
  EDIT_TRANSPORT_COMPANY: "EDIT_TRANSPORT_COMPANY",
  DELETE_TRANSPORT_COMPANY: "DELETE_TRANSPORT_COMPANY",

  // Destinations
  CREATE_DESTINATION: "CREATE_DESTINATION",
  VIEW_DESTINATION: "VIEW_DESTINATION",
  EDIT_DESTINATION: "EDIT_DESTINATION",
  DELETE_DESTINATION: "DELETE_DESTINATION",

  // Units
  CREATE_UNIT: "CREATE_UNIT",
  VIEW_UNIT: "VIEW_UNIT",
  EDIT_UNIT: "EDIT_UNIT",
  DELETE_UNIT: "DELETE_UNIT",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  ADMIN: Object.values(PERMISSIONS),
  MANAGER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_SHIPMENT,
    PERMISSIONS.VIEW_CONTAINER,
    PERMISSIONS.VIEW_TRIP,
    PERMISSIONS.VIEW_DOCUMENT,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_COMPANIES,
    PERMISSIONS.CREATE_SHIPMENT,
    PERMISSIONS.EDIT_SHIPMENT,
    PERMISSIONS.CREATE_CONTAINER,
    PERMISSIONS.EDIT_CONTAINER,
    PERMISSIONS.CREATE_TRIP,
    PERMISSIONS.EDIT_TRIP,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.VIEW_TRADER,
    PERMISSIONS.CREATE_TRADER,
    PERMISSIONS.EDIT_TRADER,
    PERMISSIONS.VIEW_GATE,
    PERMISSIONS.CREATE_GATE,
    PERMISSIONS.EDIT_GATE,
    PERMISSIONS.VIEW_PORT,
    PERMISSIONS.CREATE_PORT,
    PERMISSIONS.EDIT_PORT,
    PERMISSIONS.VIEW_DEPOT,
    PERMISSIONS.CREATE_DEPOT,
    PERMISSIONS.EDIT_DEPOT,
    PERMISSIONS.VIEW_ITEM_TYPE,
    PERMISSIONS.CREATE_ITEM_TYPE,
    PERMISSIONS.EDIT_ITEM_TYPE,
    PERMISSIONS.VIEW_COMP_ITEM,
    PERMISSIONS.CREATE_COMP_ITEM,
    PERMISSIONS.EDIT_COMP_ITEM,
    PERMISSIONS.VIEW_SUB_COMPANY,
    PERMISSIONS.CREATE_SUB_COMPANY,
    PERMISSIONS.EDIT_SUB_COMPANY,
    PERMISSIONS.VIEW_TRANSPORT_COMPANY,
    PERMISSIONS.CREATE_TRANSPORT_COMPANY,
    PERMISSIONS.EDIT_TRANSPORT_COMPANY,
    PERMISSIONS.VIEW_DESTINATION,
    PERMISSIONS.CREATE_DESTINATION,
    PERMISSIONS.EDIT_DESTINATION,
    PERMISSIONS.VIEW_UNIT,
    PERMISSIONS.CREATE_UNIT,
    PERMISSIONS.EDIT_UNIT,
  ],
  USER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_SHIPMENT,
    PERMISSIONS.VIEW_CONTAINER,
    PERMISSIONS.VIEW_TRIP,
    PERMISSIONS.VIEW_DOCUMENT,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.VIEW_TRADER,
    PERMISSIONS.VIEW_GATE,
    PERMISSIONS.VIEW_PORT,
    PERMISSIONS.VIEW_DEPOT,
    PERMISSIONS.VIEW_ITEM_TYPE,
    PERMISSIONS.VIEW_COMP_ITEM,
    PERMISSIONS.VIEW_SUB_COMPANY,
    PERMISSIONS.VIEW_TRANSPORT_COMPANY,
    PERMISSIONS.VIEW_DESTINATION,
    PERMISSIONS.VIEW_UNIT,
  ],
  GUEST: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_SHIPMENT,
    PERMISSIONS.VIEW_TRIP,
    PERMISSIONS.VIEW_TRADER,
    PERMISSIONS.VIEW_GATE,
    PERMISSIONS.VIEW_PORT,
    PERMISSIONS.VIEW_ITEM_TYPE,
  ],
};
